spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=/Users/kimhyunwoo/Spring/Wallet_aiclass
    username: admin
    password: Gusdnwkd2029@